version: '3.5'
services:
  minio:
    build: minio
    image: finance_minio:1.0.0
    command: server --console-address ":9001" /finance_data
    environment:
      MINIO_ROOT_USER: 9Z939G61IPEV0WFHWIW1
      MINIO_ROOT_PASSWORD: krPc7XIcvXPCGnZpX1BtMnmWr4OaTzXqsH+50Jd6
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - finance_ntwrk
  db:
    build: postgresql
    image: finance_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12378
    ports:
      - "5432:5432"
    networks:
      - finance_ntwrk
  pgadmin:
    build: pgadmin
    image: finance_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - finance_ntwrk
  swagger-ui:
    build: swagger-ui
    image: finance_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - finance_ntwrk

  account-scheduler-service:
    build: account-scheduler-service
    image: finance_account-scheduler-service:1.0.0
    networks:
      - finance_ntwrk
  account-service:
    build: account-service
    image: finance_account-service:1.0.0
    networks:
      - finance_ntwrk
  user-service:
    build: user-service
    image: finance_user-service:1.0.0
    networks:
      - finance_ntwrk
  classifier-service:
    build: classifier-service
    image: finance_classifier-service:1.0.0
    networks:
      - finance_ntwrk
  report-service:
    build: report-service
    image: finance_report-service:1.0.0
    networks:
      - finance_ntwrk
  telegram-service:
    build: telegram-service
    image: finance_telegram-service:1.0.0
    networks:
      - finance_ntwrk
  mail-scheduler-service:
    build: mail-scheduler-service
    image: finance_mail-scheduler-service:1.0.0
    networks:
      - finance_ntwrk
  mail-service:
    build: mail-service
    image: finance_mail-service:1.0.0
    networks:
      - finance_ntwrk
  proxy:
    build: proxy
    image: finance_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - finance_ntwrk
networks:
    finance_ntwrk:
      name: finance_ntwrk