spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/user-service?currentSchema=security
    username: postgres
    password: 12378
urls:
  email-url: "http://mail-service:8080/mail/verify"
  verify-link: "http://localhost/api/v1/user/verify/%s"

