spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/account-service?ApplicationName=TestSweetApp
    username: postgres
    password: 12378
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
urls:
  currency-url: "http://classifier-service:8080/classifier/currency/%s"
  operation-category-url : "http://classifier-service:8080/classifier/operation/category/%s"
